/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Atendente;
import Model.Comanda;
import Model.Login;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;

import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author davia
 */
public class FEditarFuncionario extends javax.swing.JFrame {

    Atendente func = new Atendente();
    Login login = new Login();
    Comanda ped = new Comanda();
    
    private void listarFunc(String nome) {
        ResultSet retornoFunc = func.consultarFuncionariosNome(nome);
        DefaultTableModel tabelaFunc = (DefaultTableModel) tblFuncionarios.getModel();
        tabelaFunc.setNumRows(0);

        try {
            do {
                tabelaFunc.addRow(new String[]{
                    retornoFunc.getString(1),
                    retornoFunc.getString(2),
                    retornoFunc.getString(3),
                    retornoFunc.getString(4),
                    retornoFunc.getString(5),
                    retornoFunc.getString(6)
                });
            } while(retornoFunc.next());
        } catch(SQLException ex) {
            Logger.getLogger(FHomeFunc.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não existem funcionários cadastradas!");
        }
    }
    
    private void limparCampos() {
        txtId.setText("");
        txtLogin.setText("");
        txtSenha.setText("");
        txtSalario.setText("");
        txtSituacao.setSelectedIndex(0);
        txtNivel.setSelectedIndex(0);
    }
    
    /**
     * Creates new form FEditarFuncionario
     */
    public FEditarFuncionario() {
        initComponents();
        
        // TABELA DE FUNCIONÁRIOS
        listarFunc("%");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIdComanda = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        txtSalario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtSituacao = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        imgBack = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtNivel = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar dados do funcionário");
        setMaximumSize(new java.awt.Dimension(1300, 620));
        setMinimumSize(new java.awt.Dimension(1300, 620));

        jPanel1.setBackground(new java.awt.Color(244, 148, 27));
        jPanel1.setMaximumSize(new java.awt.Dimension(1300, 620));
        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 620));

        lblIdComanda.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        lblIdComanda.setForeground(new java.awt.Color(255, 255, 255));
        lblIdComanda.setText("Formulário");

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/gemini_logo_white_60x60.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID:");

        txtId.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Login:");

        txtLogin.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Senha:");

        jLabel17.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Salário");

        jLabel18.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Situação:");

        btnCadastrar.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAtualizar.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tblFuncionarios.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pessoa", "Nome", "Nome Social", "Salário", "Situação", "Login"
            }
        ));
        tblFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFuncionarios);

        txtPesquisar.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        txtSenha.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N

        txtSalario.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Só inserir a senha caso deseje alterar!");

        txtSituacao.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        txtSituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Desativo" }));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pesquisar por Nome:");

        imgBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/undo.png"))); // NOI18N
        imgBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgBackMouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Nível:");

        txtNivel.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        txtNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Atendente", "Admin" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15)
                    .addComponent(jLabel10)
                    .addComponent(imgLogo)
                    .addComponent(lblIdComanda)
                    .addComponent(jLabel9)
                    .addComponent(txtLogin)
                    .addComponent(txtSenha)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtId))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(imgBack)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSituacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(40, 40, 40))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnCadastrar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAtualizar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnExcluir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(263, 263, 263)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel19))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgLogo)
                    .addComponent(imgBack))
                .addGap(18, 18, 18)
                .addComponent(lblIdComanda)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel17)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(110, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(txtSalario))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 152, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBackMouseClicked
        this.dispose();
        new FFuncionarios().setVisible(true);
    }//GEN-LAST:event_imgBackMouseClicked

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        listarFunc(txtPesquisar.getText());
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void tblFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFuncionariosMouseClicked
        int campo = tblFuncionarios.getSelectedRow();
        ResultSet retornoFunc = func.consultar(Integer.parseInt(tblFuncionarios.getValueAt(campo, 0).toString()));
        
        try {
            do {          
                txtId.setText(retornoFunc.getString(1));
                txtLogin.setText(retornoFunc.getString(6));
                txtSalario.setText(retornoFunc.getString(4));
                txtSituacao.setSelectedItem(retornoFunc.getString(5));
                txtNivel.setSelectedIndex(Integer.parseInt(retornoFunc.getString(7)));
            } while(retornoFunc.next());
        } catch(SQLException ex) {
            Logger.getLogger(FHomeFunc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblFuncionariosMouseClicked

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if(!txtLogin.getText().equals("") && !txtSenha.getText().equals("")) {         
            if(!txtId.getText().equals("")) {
                func.atualizar(
                    Integer.parseInt(txtId.getText()),
                    Double.parseDouble(txtSalario.getText()),
                    txtSituacao.getSelectedItem().toString()
                );

                String hash = "";
                try {
                    hash = login.hashing(txtSenha.getText());
                } catch (NoSuchAlgorithmException | UnsupportedEncodingException ex) {
                    Logger.getLogger(FEditarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
                }
                login.cadastrar(
                    Integer.parseInt(txtId.getText()),
                    txtLogin.getText(),
                    hash,
                    txtNivel.getSelectedIndex()
                );

                JOptionPane.showMessageDialog(null, "Dados cadastrados com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "Selecione uma pessoa sem dados ou insira o ID Pessoa!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Preencha os campos login e senha!");
        }
        
        limparCampos();
        listarFunc("%");
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        if(!txtId.getText().equals("") && !txtLogin.getText().equals("")) {  
            func.atualizar(
                Integer.parseInt(txtId.getText()),
                Double.parseDouble(txtSalario.getText()),
                txtSituacao.getSelectedItem().toString()
            );
            
            String hash = "";
            if(!txtSenha.getText().equals("")) {
                try {
                    hash = login.hashing(txtSenha.getText());
                } catch (NoSuchAlgorithmException | UnsupportedEncodingException ex) {
                    Logger.getLogger(FEditarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                ResultSet retornoSenha = login.consultarSenha(txtLogin.getText());
                try {
                    hash = retornoSenha.getString(1);
                } catch (SQLException ex) {
                    Logger.getLogger(FEditarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            login.atualizar(
                Integer.parseInt(txtId.getText()),
                txtLogin.getText(),
                hash,
                txtNivel.getSelectedIndex()
            );
               
            JOptionPane.showMessageDialog(null, "Dados atualizados com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Preencha os campos necessários!");
        }
        
        limparCampos();
        listarFunc("%");
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(!txtId.getText().equals("") && !txtLogin.getText().equals("")) {
            login.excluir(Integer.parseInt(txtId.getText()));
            
            ResultSet retornoFunc = func.buscarIdPeloLogin(txtLogin.getText());
            try {
                ped.retirarAtendente(Integer.parseInt(retornoFunc.getString(1)));
            } catch (SQLException ex) {
                Logger.getLogger(FEditarPessoa.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            func.excluir(Integer.parseInt(txtId.getText()));
               
            JOptionPane.showMessageDialog(null, "Dados excluídos com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Preencha os campos necessários!");
        }
        
        limparCampos();
        listarFunc("%");
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FEditarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FEditarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FEditarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FEditarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FEditarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel imgBack;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIdComanda;
    private javax.swing.JTable tblFuncionarios;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JComboBox txtNivel;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JComboBox txtSituacao;
    // End of variables declaration//GEN-END:variables
}
