/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Atendente;

import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fatec_aluno
 */
public class FFuncionarios extends javax.swing.JFrame {
    
    Atendente func = new Atendente();

    /**
     * Creates new form FFuncionarios
     */
    public FFuncionarios() {
        initComponents();
        
        // TABELA DE FUNCIONÁRIOS
        ResultSet retornoFunc = func.listarFuncionariosNome("%");
        DefaultTableModel tabelaFunc = (DefaultTableModel) tblFuncionarios.getModel();
        tabelaFunc.setNumRows(0);

        try {
            do {
                tabelaFunc.addRow(new String[]{retornoFunc.getString(1), retornoFunc.getString(2), retornoFunc.getString(3), retornoFunc.getString(4), retornoFunc.getString(5), retornoFunc.getString(6)});
            } while(retornoFunc.next());
        } catch(SQLException ex) {
            Logger.getLogger(FHomeFunc.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não existem funcionários cadastrados!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuBar = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        imgHome = new javax.swing.JLabel();
        imgComanda = new javax.swing.JLabel();
        imgEstoque = new javax.swing.JLabel();
        imgFuncionarios = new javax.swing.JLabel();
        imgVendas = new javax.swing.JLabel();
        imgSair = new javax.swing.JLabel();
        lblIdComanda = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JTextField();
        btnFormPessoa = new javax.swing.JButton();
        btnFormFuncionario = new javax.swing.JButton();
        btnFormEndereco = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Funcionários e Login");
        setMaximumSize(new java.awt.Dimension(1300, 620));
        setMinimumSize(new java.awt.Dimension(1300, 620));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(244, 148, 27));
        jPanel1.setMaximumSize(new java.awt.Dimension(1300, 620));
        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 620));

        menuBar.setBackground(new java.awt.Color(0, 0, 0));
        menuBar.setMaximumSize(new java.awt.Dimension(96, 620));
        menuBar.setMinimumSize(new java.awt.Dimension(96, 620));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/gemini_logo_white_60x60.png"))); // NOI18N

        imgHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/home.png"))); // NOI18N
        imgHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgHomeMouseClicked(evt);
            }
        });

        imgComanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/notes.png"))); // NOI18N
        imgComanda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgComanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgComandaMouseClicked(evt);
            }
        });

        imgEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/boxes.png"))); // NOI18N
        imgEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgEstoqueMouseClicked(evt);
            }
        });

        imgFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/employee.png"))); // NOI18N
        imgFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        imgVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/sales.png"))); // NOI18N
        imgVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgVendasMouseClicked(evt);
            }
        });

        imgSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/open-door.png"))); // NOI18N
        imgSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(imgLogo)
                .addGap(18, 18, 18))
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgComanda)
                    .addComponent(imgHome)
                    .addComponent(imgEstoque)
                    .addComponent(imgFuncionarios)
                    .addComponent(imgVendas)
                    .addComponent(imgSair))
                .addGap(32, 32, 32))
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(imgLogo)
                .addGap(80, 80, 80)
                .addComponent(imgHome)
                .addGap(40, 40, 40)
                .addComponent(imgComanda)
                .addGap(40, 40, 40)
                .addComponent(imgEstoque)
                .addGap(40, 40, 40)
                .addComponent(imgFuncionarios)
                .addGap(40, 40, 40)
                .addComponent(imgVendas)
                .addGap(40, 40, 40)
                .addComponent(imgSair)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        lblIdComanda.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        lblIdComanda.setForeground(new java.awt.Color(255, 255, 255));
        lblIdComanda.setText("Funcionários e Login");

        tblFuncionarios.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pessoa", "Nome", "RG", "CPF", "Situação", "Login"
            }
        ));
        jScrollPane1.setViewportView(tblFuncionarios);

        txtPesquisar.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        btnFormPessoa.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnFormPessoa.setText("Formulário de Dados Pessoais");
        btnFormPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormPessoaActionPerformed(evt);
            }
        });

        btnFormFuncionario.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnFormFuncionario.setText("Formulário de Funcionários");
        btnFormFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormFuncionarioActionPerformed(evt);
            }
        });

        btnFormEndereco.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnFormEndereco.setText("Formulário de Endereços");
        btnFormEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormEnderecoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Clique nos botões para criar, alterar ou excluir dados");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pesquisar:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblIdComanda)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btnFormPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFormFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFormEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblIdComanda)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnFormPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnFormFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnFormEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgHomeMouseClicked
        this.dispose();
        new FHomeAdmin().setVisible(true);
    }//GEN-LAST:event_imgHomeMouseClicked

    private void imgComandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgComandaMouseClicked
        this.dispose();
        new FComandaAdmin().setVisible(true);
    }//GEN-LAST:event_imgComandaMouseClicked

    private void imgSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgSairMouseClicked
        this.dispose();
        new FLogin().setVisible(true);
    }//GEN-LAST:event_imgSairMouseClicked

    private void imgEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgEstoqueMouseClicked
        this.dispose();
        new FProdutos().setVisible(true);
    }//GEN-LAST:event_imgEstoqueMouseClicked

    private void imgVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgVendasMouseClicked
        this.dispose();
        new FVendas().setVisible(true);
    }//GEN-LAST:event_imgVendasMouseClicked

    private void btnFormPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormPessoaActionPerformed
        this.dispose();
        new FEditarPessoa().setVisible(true);
    }//GEN-LAST:event_btnFormPessoaActionPerformed

    private void btnFormFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormFuncionarioActionPerformed
        this.dispose();
        new FEditarFuncionario().setVisible(true);
    }//GEN-LAST:event_btnFormFuncionarioActionPerformed

    private void btnFormEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormEnderecoActionPerformed
        this.dispose();
        new FEditarEndereco().setVisible(true);
    }//GEN-LAST:event_btnFormEnderecoActionPerformed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        ResultSet retornoFunc = func.listarFuncionariosNome(txtPesquisar.getText());
        DefaultTableModel tabelaFunc = (DefaultTableModel) tblFuncionarios.getModel();
        tabelaFunc.setNumRows(0);

        try {
            do {
                tabelaFunc.addRow(new String[]{retornoFunc.getString(1), retornoFunc.getString(2), retornoFunc.getString(3), retornoFunc.getString(4), retornoFunc.getString(5), retornoFunc.getString(6)});
            } while(retornoFunc.next());
        } catch(SQLException ex) {
            Logger.getLogger(FHomeFunc.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não existem funcionários cadastrados!");
        }
    }//GEN-LAST:event_txtPesquisarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormEndereco;
    private javax.swing.JButton btnFormFuncionario;
    private javax.swing.JButton btnFormPessoa;
    private javax.swing.JLabel imgComanda;
    private javax.swing.JLabel imgEstoque;
    private javax.swing.JLabel imgFuncionarios;
    private javax.swing.JLabel imgHome;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel imgSair;
    private javax.swing.JLabel imgVendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIdComanda;
    private javax.swing.JPanel menuBar;
    private javax.swing.JTable tblFuncionarios;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
